# Description: Configuration file for training the model


max_iter: 500
num_samples: 16384
anneal_iter: 10000
annealing: true
show_iter: 5


prior:
    name: gaussian
    dim: 2
    path: run-ls9lgtc3-model.pth:v0

criterion: cross_entropy

optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.0001

scheduler:
    name: ReduceLROnPlateau
    lr_factor: 0.1
    lr_patience: 5