# Description: Configuration file for training the model


epochs: 100
anneal_iter: 10000
annealing: true
show_iter: 10
batch_size: 512
reduction: PCA
epoch_switch:
    - 10

prior:
    name: gaussian
    dim: 1
    trainable: false
    path: run-hsagfpjv-model.pth:v0

dataset:
    name: TwoMoons
    params:
        num_samples: 512

model:
    flow1:
        name: spline_flow
        dim: 1
        params:
            latent_size: 1
            K: 3
            hidden_units: 128
            hidden_layers: 3
#    flow2:
#        name: spline_flow
#        dim: 10
#        params:
#            latent_size: 20
#            K: 3
#            hidden_units: 128
#            hidden_layers: 3
    flow3:
        name: spline_flow
        dim: 1
        params:
            latent_size: 2
            K: 6
            hidden_units: 128
            hidden_layers: 3


criterion: cross_entropy

optimizer:
    name: Adam
    lr: 0.0003
    weight_decay: 0.00001

scheduler:
    name: ReduceLROnPlateau
    lr_factor: 0.5
    min_lr: 0.00001
    lr_patience: 20